### NumPy
+ Based on C
+ lists are very slow, NumPy has arrays instead.
+ These arrays have same element.

In [2]:
import numpy as np
# Create array
li = [1,2,3]
a = np.array(li)
print(type(a))

<class 'numpy.ndarray'>


0. means value is Decimal.

In [12]:
a = np.zeros((3,4), dtype = int)
print(a)
print(type(a[0]))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
<class 'numpy.ndarray'>


In [6]:
a = np.ones(3)
a

array([1., 1., 1.])

In [9]:
a = np.full(3,fill_value=9)
a


array([9, 9, 9])

+ np.random.rand(): Takes dimensions of array
+ np.random.randint() : Takes low and high value, gives integer, if one value is given only it takes that as the high value, this is followed by dimensions of the array.

In [3]:
a = np.random.randint(30,50,(3,4,5,6))
a

array([[[[31, 37, 30, 38, 46, 37],
         [44, 38, 46, 34, 48, 33],
         [48, 41, 30, 44, 46, 46],
         [40, 37, 40, 40, 39, 40],
         [30, 38, 33, 33, 31, 35]],

        [[44, 46, 35, 40, 41, 32],
         [33, 30, 39, 40, 31, 33],
         [42, 48, 34, 49, 38, 33],
         [36, 44, 41, 45, 42, 42],
         [49, 36, 41, 38, 40, 34]],

        [[41, 49, 44, 47, 40, 44],
         [30, 35, 34, 47, 43, 37],
         [34, 45, 39, 49, 45, 40],
         [46, 48, 45, 40, 34, 47],
         [44, 48, 47, 43, 45, 31]],

        [[46, 38, 49, 44, 47, 30],
         [46, 42, 42, 47, 46, 36],
         [41, 31, 36, 38, 32, 35],
         [35, 47, 45, 33, 49, 32],
         [30, 35, 32, 36, 36, 36]]],


       [[[42, 33, 49, 43, 46, 40],
         [39, 31, 32, 44, 45, 46],
         [30, 31, 40, 31, 34, 49],
         [45, 34, 45, 43, 30, 39],
         [36, 49, 46, 37, 44, 41]],

        [[35, 42, 41, 40, 34, 39],
         [45, 30, 48, 46, 30, 30],
         [30, 47, 42, 48, 37, 36],
        

In [15]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

+ np.linspace: Similar to arange but it gives control over the number of evenly spaced values to be printed. arange gives control over the step value rather than number of values.


In [16]:
a = np.linspace(3,4,1000)
a

array([3.        , 3.001001  , 3.002002  , 3.003003  , 3.004004  ,
       3.00500501, 3.00600601, 3.00700701, 3.00800801, 3.00900901,
       3.01001001, 3.01101101, 3.01201201, 3.01301301, 3.01401401,
       3.01501502, 3.01601602, 3.01701702, 3.01801802, 3.01901902,
       3.02002002, 3.02102102, 3.02202202, 3.02302302, 3.02402402,
       3.02502503, 3.02602603, 3.02702703, 3.02802803, 3.02902903,
       3.03003003, 3.03103103, 3.03203203, 3.03303303, 3.03403403,
       3.03503504, 3.03603604, 3.03703704, 3.03803804, 3.03903904,
       3.04004004, 3.04104104, 3.04204204, 3.04304304, 3.04404404,
       3.04504505, 3.04604605, 3.04704705, 3.04804805, 3.04904905,
       3.05005005, 3.05105105, 3.05205205, 3.05305305, 3.05405405,
       3.05505506, 3.05605606, 3.05705706, 3.05805806, 3.05905906,
       3.06006006, 3.06106106, 3.06206206, 3.06306306, 3.06406406,
       3.06506507, 3.06606607, 3.06706707, 3.06806807, 3.06906907,
       3.07007007, 3.07107107, 3.07207207, 3.07307307, 3.07407

In [18]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

+ eye(): makes identity matrix, can also make rectangular matrix
+ identity(): can make identity matrix but square only, not rectangular.

+ for numpy arrays a = a+1 adds 1 to all array elements, no loop required plus a lot faster than iterating with loop.
+ This happens since this numpy array makes chunks and adds 1 together. This process is known as vectorization.
+ The id too changes in this method.

In [21]:
print(id(a))
a = a+1
print(id(a))
print(a)
a = a*a
print(a)

1580947571376
1580947571616
[[4. 3. 3. 3.]
 [3. 4. 3. 3.]
 [3. 3. 4. 3.]]
[[16.  9.  9.  9.]
 [ 9. 16.  9.  9.]
 [ 9.  9. 16.  9.]]


+ np arrays allow not only a[1][0] but also a[1,0] i.e comma also works.
+ in normal lists row slicing doesn't work i.e . a[0:2][1] doesn't work. for li[0:2][2] will give error since 2 is not in range (li is a 2d list with 3 rows and 3 columns) li[0:3][2] will work but give the second row instead of column which was the expected result.
+ Row wise slicing however,does work for arrays.
### Boolean Indexing
+ li1>15 gives True or False cooresponding to each value in array.


In [23]:
ans = a>15
ans
print(a[ans])

[16. 16. 16.]


+ for indices we have np.where

In [5]:
ans = np.where(a>15)
print(ans)
t = a[ans]
print(t)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2

In [106]:
import csv
f_o = open(r'C:\Users\venug\Downloads\terrorismData.csv')
data = csv.reader(f_o,skipinitialspace = True)
data = list(data)
d = np.array(data)
s =np.array(d[:,[3,10]])

print(np.shape(s))
t=np.delete(s,[0,1])
print('       ')
t = np.reshape(t,(-1,2))
print(t)
country = s[:,0]
killed = s[:,1]
country

(154, 2)
       
[['Dominican Republic' '1']
 ['Mexico' '0']
 ['Philippines' '1']
 ['Greece' '']
 ['Japan' '']
 ['United States' '0']
 ['Uruguay' '0']
 ['United States' '0']
 ['United States' '0']
 ['United States' '0']
 ['United States' '0']
 ['United States' '0']
 ['Italy' '0']
 ['United States' '0']
 ['United States' '0']
 ['East Germany (GDR)' '']
 ['Ethiopia' '1']
 ['United States' '0']
 ['United States' '0']
 ['United States' '0']
 ['United States' '0']
 ['Uruguay' '0']
 ['Iran' '']
 ['United Kingdom' '1']
 ['United Kingdom' '1']
 ['West Germany (FRG)' '0']
 ['United Kingdom' '1']
 ['United Kingdom' '1']
 ['Spain' '']
 ['Turkey' '']
 ['Turkey' '0']
 ['Spain' '']
 ['Sweden' '']
 ['Turkey' '']
 ['Turkey' '0']
 ['Turkey' '0']
 ['West Germany (FRG)' '0']
 ['United Kingdom' '1']
 ['Italy' '1']
 ['Turkey' '0']
 ['Austria' '4']
 ['United States' '0']
 ['United States' '0']
 ['Colombia' '0']
 ['Ireland' '2']
 ['Dominican Republic' '0']
 ['United Kingdom' '1']
 ['United States' '1']
 ['Un

array(['Country', 'Dominican Republic', 'Mexico', 'Philippines', 'Greece',
       'Japan', 'United States', 'Uruguay', 'United States',
       'United States', 'United States', 'United States', 'United States',
       'Italy', 'United States', 'United States', 'East Germany (GDR)',
       'Ethiopia', 'United States', 'United States', 'United States',
       'United States', 'Uruguay', 'Iran', 'United Kingdom',
       'United Kingdom', 'West Germany (FRG)', 'United Kingdom',
       'United Kingdom', 'Spain', 'Turkey', 'Turkey', 'Spain', 'Sweden',
       'Turkey', 'Turkey', 'Turkey', 'West Germany (FRG)',
       'United Kingdom', 'Italy', 'Turkey', 'Austria', 'United States',
       'United States', 'Colombia', 'Ireland', 'Dominican Republic',
       'United Kingdom', 'United States', 'United Kingdom',
       'United Kingdom', 'Colombia', 'Greece', 'Greece', 'United States',
       'Colombia', 'France', 'West Germany (FRG)', 'West Germany (FRG)',
       'Austria', 'United Kingdom', 'Unit

+ np has functions as max, min, sum and so on
+ axis 0 for column operations and 1 for row operations

In [31]:
np.random.seed(0)
a = np.random.rand(1,5)
print(a)
print(np.where(a>.6))
t = a>.6
print(t)
a[a>.6]

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]]
(array([0, 0], dtype=int64), array([1, 2], dtype=int64))
[[False  True  True False False]]


array([0.71518937, 0.60276338])

## Boolean Indexing in 2d arrays

In [40]:
np.random.seed(0)
a = np.random.rand(4,4)
a = a*10
a = a.astype(int)
a[a>6] = -1
print(a)

[[ 5 -1  6  5]
 [ 4  6  4 -1]
 [-1  3 -1  5]
 [ 5 -1  0  0]]


## Broadcasting

+ In case of matrices if dimensions are not the same operations cannot be performed. However due to broadcasting if one of the dimensions is one and the other is the same we will still be able to perform all operations.

+ In case of compatibility the matrix is stretched along the dimension with 1 to match the dimensions of the other matrix

In [43]:
a = np.random.randint(1,10,(1,3))
b = np.random.randint(1,10,(5,1))
c = a+b
print(a)
print(b)
print(c)

[[2 4 4]]
[[4]
 [8]
 [1]
 [2]
 [1]]
[[ 6  8  8]
 [10 12 12]
 [ 3  5  5]
 [ 4  6  6]
 [ 3  5  5]]


## Questions

In [46]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [50]:
b = np.arange(0,9)
b = b.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [123]:
def n_largest_values(n,a):
    a = np.sort(a)
    b = a[-n:]
    return b
np.random.seed(0)
a = np.random.randint(10,size = 10)

b = n_largest_values(3,a)
print(a)
print(b)


[5 0 3 3 7 9 3 5 2 4]
[5 7 9]


[[5 9 8 9 4 3 0 3 5 0]]


IndexError: index 3 is out of bounds for axis 0 with size 1

In [102]:
a = [3, 1, 2, 8, 9]
print(a)
print(a[-2:])

[3, 1, 2, 8, 9]
[8, 9]


In [124]:
a = np.array([1,2,0,0,4,0])
t = np.where(a>0)
print(t)

(array([0, 1, 4], dtype=int64),)


In [128]:
a = np.random.randint(10,size = 10)
print(a)
t = np.where(a%3 == 0)
b = a[a%3 == 0]
print(t)
print(b)

[9 9 0 4 7 3 2 7 2 0]
(array([0, 1, 2, 5, 9], dtype=int64),)
[9 9 0 3 0]


In [129]:
np.random.seed(0)
a = np.random.randint(10,size = 10)
print(a)
a[a%2!=0] = -1
print(a)

[5 0 3 3 7 9 3 5 2 4]
[-1  0 -1 -1 -1 -1 -1 -1  2  4]


In [158]:
a = np.random.randint(10,size = (10))
print(a)
t = np.max(a)
print(t)
a[a == t] = 0
print(a)

[8 7 7 1 8 4 7 0 4 9]
9
[8 7 7 1 8 4 7 0 4 0]


In [163]:
a = np.random.randint(10,size = (10))
print(a)
print(a[(a>=3) & (a<=8)])


[7 8 8 7 0 8 6 8 9 8]
[7 8 8 7 8 6 8 8]


In [7]:
a = np.random.randint(10,size = (4,5))
print(a)
t = np.argsort(a[:,1],axis = 0)
print(t)
a = a[t]
print(a)
a[:,2] = np.sort(a[:,2])
print(a)

[[2 8 3 3 6]
 [5 0 9 2 5]
 [5 3 6 8 3]
 [0 5 0 4 6]]
[1 2 3 0]
[[5 0 9 2 5]
 [5 3 6 8 3]
 [0 5 0 4 6]
 [2 8 3 3 6]]
[[5 0 0 2 5]
 [5 3 3 8 3]
 [0 5 6 4 6]
 [2 8 9 3 6]]


In [5]:
a = np.random.randint(-20,20, size = 40)
print(a)
n = 5
t = np.abs(a-n)
s= np.argmin(t)
print(s)
print(a[s])

[-14  17 -15   4 -18  11  14  15  18  -5   8  -2 -19  -9   6 -20  -4  10
   5  19  -6 -19  -1  14  -8 -11  17 -18   4  -3 -16   5  -8  15 -12 -10
 -13   8  17  15]
18
5


## Questions using Dataset